spring:
  config:
    import: optional:configserver:http://localhost:8889
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: notificationRequest:com.fintech.notification.dto.NotificationRequest
        spring.json.use.type.headers: false


user:
  service:
    url: http://localhost:8090



management:
  endpoints:
    web:
      exposure:
        include: "*"
