apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: notification
data:
  application.yaml: |
    spring:
      application:
        name: notification-service
      config:
        import: optional:configserver:http://config-server:8888
      user-service:
        url: http://user-service:8090/api/users