apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: fintech
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: notification-service