apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: fintech
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8085
  selector:
    app: notification-service