apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: notification-service